export const homePalette = {
  background: '#F9F8FF',
  primary: '#4880FF',
  primaryDeep: '#283351',
  primarySoft: '#EEF3FF',
  secondary: '#918BFF',
  secondarySoft: '#B8A0FF',
  success: '#13A36F',
  warning: '#FF8A3D'
};

export const homeClasses = {
  barGroup: 'flex-1 items-center gap-1',
  barLabel: 'text-xs font-extrabold text-textMuted',
  barTrack: 'h-[120px] w-full justify-end overflow-hidden rounded-2xl bg-[#EEF3FF]',
  barValue: 'text-[11px] font-black text-[#283351]',
  chart: 'mt-4 h-[172px] flex-row items-end gap-2',
  chartCard: 'rounded-3xl border-[#E8ECFF]',
  connectionButton: 'mt-1 flex-row items-center gap-1 self-start',
  connectionButtonText: 'text-[13px] font-black text-[#ba1a1a]',
  consumptionCard: 'overflow-hidden rounded-3xl border-[#4880FF] bg-[#4880FF]',
  consumptionFooter: 'mt-6 flex-row items-center gap-2',
  consumptionLabel: 'text-[13px] font-black uppercase text-[#EAF0FF]',
  consumptionStatus: 'flex-1 text-[15px] font-black text-surface',
  consumptionTop: 'flex-row items-start justify-between',
  content: 'gap-4 bg-[#F9F8FF] p-4 pt-6 pb-[124px]',
  deviceListCard: 'min-h-[78px] flex-row items-center gap-4 rounded-3xl border border-[#EEF1FF] bg-surface p-4 shadow-sm',
  deviceListCardInactive: 'opacity-60',
  deviceListContent: 'flex-1',
  deviceListIcon: 'h-12 w-12 items-center justify-center rounded-full bg-[#EEF3FF]',
  deviceListIconInactive: 'bg-[#EEF0F7]',
  deviceListName: 'text-base font-black text-[#283351]',
  deviceListNameInactive: 'text-textMuted',
  deviceListStatus: 'mt-0.5 text-[13px] font-black',
  deviceListStatusOffline: 'text-textMuted',
  deviceListStatusOnline: 'text-[#13A36F]',
  devicesList: 'gap-4',
  devicesSection: 'relative gap-4',
  emptyCard: 'mt-6 items-center rounded-3xl border-[#E8ECFF] py-8',
  emptyIcon: 'h-[76px] w-[76px] items-center justify-center rounded-full bg-[#EEF3FF]',
  emptyText: 'mt-2 max-w-[280px] text-center text-[15px] font-bold leading-[22px] text-textMuted',
  emptyTitle: 'mt-4 text-center text-[22px] font-black text-[#283351]',
  floatingAddButton: 'absolute bottom-4 right-4 h-[38px] w-[38px] items-center justify-center rounded-control bg-[#918BFF] shadow-md',
  greeting: 'text-sm font-bold text-textMuted',
  healthOffline: 'bg-[#FFECEC]',
  healthOfflineText: 'text-[#ba1a1a]',
  healthOk: 'bg-surface',
  healthPill: 'flex-row items-center gap-1 rounded-full px-2 py-1',
  healthText: 'text-xs font-black text-[#4880FF]',
  header: 'flex-row items-center justify-between gap-4',
  headerText: 'flex-1',
  headerTitle: 'mt-1 text-[26px] font-black leading-[31px] text-[#283351]',
  infoBody: 'mt-1 text-[13px] font-bold leading-[19px] text-textMuted',
  infoCard: 'flex-row items-start gap-4 rounded-3xl border-[#E8ECFF] border-l-4 border-l-[#4880FF]',
  infoContent: 'flex-1',
  infoIcon: 'h-11 w-11 items-center justify-center rounded-2xl bg-[#EEF3FF]',
  infoLabel: 'text-xs font-black uppercase text-textMuted',
  infoTitle: 'mt-0.5 text-lg font-black text-[#283351]',
  insightBody: 'mt-1 text-sm font-bold leading-[21px] text-[#F6F3FF]',
  insightCard: 'rounded-3xl border-[#918BFF] bg-[#918BFF]',
  insightLabel: 'text-xs font-black uppercase text-[#F0ECFF]',
  insightTitle: 'mt-1 text-xl font-black text-surface',
  lastUpdate: 'mt-1 text-[13px] font-bold text-[#EAF0FF]',
  miniBar: 'flex-1 rounded-lg',
  miniBars: 'mt-6 h-[104px] flex-row items-end gap-2',
  normalIndicator: 'h-2.5 w-2.5 rounded-full bg-[#A8FFD8]',
  offlineBody: 'text-[13px] font-bold leading-[19px] text-textMuted',
  offlineCard: 'items-start gap-2 rounded-3xl border-[#FFDADA] bg-[#FFF6F6]',
  offlineContent: 'gap-1',
  offlineTitle: 'text-base font-black leading-[22px] text-[#283351]',
  powerRow: 'mt-1 flex-row items-end',
  powerUnit: 'mb-[9px] ml-1 text-lg font-black text-[#EAF0FF]',
  powerValue: 'text-[58px] font-black leading-[64px] text-surface',
  primaryButton: 'mt-6 flex-row items-center gap-2 rounded-2xl bg-[#4880FF] px-6 py-4',
  primaryButtonText: 'text-[15px] font-black text-surface',
  profileButton: 'h-12 w-12 items-center justify-center rounded-full border border-[#E5EAFF] bg-surface shadow-sm',
  quickAction: 'min-h-16 flex-1 basis-[46%] flex-row items-center gap-2 rounded-2xl border border-[#E8ECFF] bg-surface p-4 shadow-sm',
  quickGrid: 'flex-row flex-wrap gap-4',
  quickIcon: 'h-[34px] w-[34px] items-center justify-center rounded-control bg-[#EEF3FF]',
  quickLabel: 'flex-1 text-[13px] font-black text-[#283351]',
  quickSection: 'gap-4',
  summaryGrid: 'gap-4'
};
