export const pairDevicePalette = {
  primary: '#4880FF',
  secondary: '#918BFF',
  secondarySoft: '#B8A0FF',
  success: '#13A36F',
  warning: '#FF8A3D',
  danger: '#ba1a1a',
  text: '#283351'
};

export const pairDeviceClasses = {
  actionButton: 'items-center rounded-2xl bg-[#4880FF] px-5 py-4',
  actionButtonSecondary: 'items-center rounded-2xl border border-[#E8ECFF] bg-surface px-5 py-4',
  actionButtonSecondaryText: 'text-[15px] font-black text-[#4880FF]',
  actionButtonText: 'text-[15px] font-black text-surface',
  card: 'rounded-3xl border-[#E8ECFF]',
  connectionStep: 'flex-row items-center gap-3 rounded-2xl bg-[#F7F8FF] p-3',
  connectionStepIcon: 'h-8 w-8 items-center justify-center rounded-full bg-[#EEF3FF]',
  connectionStepText: 'flex-1 text-sm font-bold text-[#283351]',
  content: 'gap-4 bg-[#F9F8FF] p-4 pb-[124px]',
  errorButton: 'flex-1 items-center rounded-2xl bg-[#4880FF] px-4 py-3',
  errorButtonSecondary: 'flex-1 items-center rounded-2xl border border-[#E8ECFF] bg-surface px-4 py-3',
  errorButtonSecondaryText: 'text-sm font-black text-[#4880FF]',
  errorButtonText: 'text-sm font-black text-surface',
  errorText: 'mt-2 text-[13px] font-black text-[#ba1a1a]',
  fieldInput: 'min-h-[52px] flex-1 rounded-2xl border border-[#E8ECFF] bg-[#F7F8FF] px-4 text-base font-bold text-[#283351]',
  fieldLabel: 'text-sm font-black text-[#283351]',
  fieldWrapper: 'gap-2',
  helperText: 'mt-3 text-sm font-bold leading-5 text-textMuted',
  iconHero: 'h-[74px] w-[74px] items-center justify-center rounded-3xl bg-[#EEF3FF]',
  inputAction: 'h-[52px] w-[52px] items-center justify-center rounded-2xl border border-[#E8ECFF] bg-surface',
  notice: 'flex-row items-start gap-3 rounded-3xl border-[#E8ECFF] bg-[#EEF3FF]',
  noticeText: 'flex-1 text-sm font-bold leading-5 text-textMuted',
  progressBar: 'h-2 overflow-hidden rounded-full bg-[#E8ECFF]',
  progressFill: 'h-full rounded-full bg-[#4880FF]',
  stepCircle: 'h-8 w-8 items-center justify-center rounded-full border border-[#E8ECFF] bg-surface',
  stepCircleActive: 'bg-[#4880FF]',
  stepCircleDone: 'bg-[#13A36F]',
  stepLabel: 'mt-2 text-[11px] font-black text-textMuted',
  stepLabelActive: 'text-[#4880FF]',
  stepList: 'mt-5 gap-3',
  stepRow: 'flex-row items-center gap-3',
  stepRowIcon: 'h-9 w-9 items-center justify-center rounded-xl bg-[#EEF3FF]',
  stepRowText: 'flex-1 text-sm font-bold leading-5 text-[#283351]',
  subtitle: 'mt-2 text-[15px] font-bold leading-[22px] text-textMuted',
  successBadge: 'self-start rounded-full bg-[#E9FFF5] px-3 py-1',
  successBadgeText: 'text-xs font-black uppercase text-[#13A36F]',
  summaryCard: 'gap-2 rounded-2xl border-[#E8ECFF] bg-[#F7F8FF] p-4',
  summaryLabel: 'text-xs font-black uppercase text-textMuted',
  summaryTitle: 'text-lg font-black text-[#283351]',
  title: 'text-[24px] font-black leading-8 text-[#283351]'
};
