export const alertsPalette = {
  background: '#F9F8FF',
  primary: '#4880FF',
  primarySoft: '#EEF3FF',
  secondary: '#918BFF',
  text: '#283351',
  success: '#13A36F',
  warning: '#FF8A3D'
};

export const alertsClasses = {
  alertCard: 'flex-row items-start gap-3 rounded-3xl border-[#E8ECFF]',
  alertContent: 'flex-1',
  alertDate: 'text-xs font-bold text-textMuted',
  alertDescription: 'mt-2 text-sm font-bold leading-5 text-textMuted',
  alertIcon: 'h-11 w-11 items-center justify-center rounded-2xl',
  alertMeta: 'mt-2 flex-row flex-wrap items-center gap-2',
  alertTitle: 'text-base font-black text-[#283351]',
  badge: 'rounded-full px-2 py-1',
  badgeText: 'text-[11px] font-black uppercase',
  content: 'gap-4 bg-[#F9F8FF] p-4 pt-6 pb-[124px]',
  detailActions: 'mt-4 flex-row gap-3',
  detailBody: 'mt-1 text-sm font-bold leading-5 text-textMuted',
  detailButtonPrimary: 'flex-1 items-center rounded-2xl bg-[#4880FF] px-4 py-3',
  detailButtonPrimaryText: 'text-sm font-black text-surface',
  detailButtonSecondary: 'flex-1 items-center rounded-2xl border border-[#E8ECFF] bg-[#EEF3FF] px-4 py-3',
  detailButtonSecondaryText: 'text-sm font-black text-[#4880FF]',
  detailCard: 'max-h-[86%] rounded-3xl border-[#E8ECFF]',
  detailHeader: 'flex-row items-start justify-between gap-4',
  detailOverlay: 'flex-1 justify-end bg-black/30 p-4',
  detailSection: 'mt-4',
  detailSubtitle: 'mt-1 text-sm font-bold text-textMuted',
  detailTitle: 'flex-1 text-[22px] font-black leading-7 text-[#283351]',
  deviceLabel: 'text-xs font-black uppercase text-[#4880FF]',
  emptyCard: 'mt-6 items-center rounded-3xl border-[#E8ECFF] py-8',
  emptyIcon: 'h-[72px] w-[72px] items-center justify-center rounded-full bg-[#E9FFF5]',
  emptyText: 'mt-2 text-center text-[15px] font-bold leading-[22px] text-textMuted',
  emptyTitle: 'mt-4 text-center text-[21px] font-black text-[#283351]',
  filterChip: 'min-h-[40px] rounded-full border border-[#E8ECFF] bg-surface px-4 items-center justify-center',
  filterChipActive: 'border-[#4880FF] bg-primary',
  filterChipText: 'text-sm font-black text-textMuted',
  filterChipTextActive: 'text-white',
  filters: 'flex-row flex-wrap gap-2',
  header: 'gap-1',
  headerStatus: 'mt-1 text-[13px] font-black text-[#4880FF]',
  highlightedCard: 'rounded-3xl border-[#918BFF] bg-[#918BFF]',
  highlightedDescription: 'mt-2 text-sm font-bold leading-5 text-[#F6F3FF]',
  highlightedFooter: 'mt-4 flex-row items-center justify-between',
  highlightedLabel: 'text-xs font-black uppercase text-[#F0ECFF]',
  highlightedTitle: 'mt-1 text-xl font-black text-surface',
  list: 'gap-3',
  modalClose: 'h-9 w-9 items-center justify-center rounded-full bg-[#EEF3FF]',
  noDeviceButton: 'mt-6 rounded-2xl bg-[#4880FF] px-6 py-4',
  noDeviceButtonText: 'text-[15px] font-black text-surface',
  offlineNotice: 'flex-row items-start gap-2 rounded-3xl border-[#FFE2C4] bg-[#FFF8EF]',
  offlineNoticeBody: 'mt-0.5 text-[13px] font-bold leading-[19px] text-textMuted',
  offlineNoticeText: 'flex-1',
  offlineNoticeTitle: 'text-[15px] font-black text-[#283351]',
  recommendationAction: 'mt-5 self-start rounded-2xl bg-surface px-5 py-3',
  recommendationActionText: 'text-sm font-black text-[#4880FF]',
  recommendationCard: 'relative overflow-hidden rounded-3xl border-[#918BFF] bg-[#7E80FF]',
  recommendationDescription: 'mt-3 max-w-[282px] text-[15px] font-bold leading-[22px] text-[#F3F0FF]',
  recommendationIcon: 'absolute -bottom-3 right-4 opacity-20',
  recommendationTitle: 'text-[21px] font-black text-surface',
  sectionBody: 'mt-1 text-sm font-bold leading-5 text-textMuted',
  sectionLabel: 'text-xs font-black uppercase text-textMuted',
  severityHigh: 'bg-[#FFECEC]',
  severityHighText: 'text-[#ba1a1a]',
  severityLow: 'bg-[#EEF3FF]',
  severityLowText: 'text-[#4880FF]',
  severityMedium: 'bg-[#FFF4E8]',
  severityMediumText: 'text-[#B65F00]',
  statusResolved: 'bg-[#E9FFF5]',
  statusResolvedText: 'text-[#13A36F]',
  statusSeen: 'bg-[#EEF3FF]',
  statusSeenText: 'text-[#4880FF]',
  statusNew: 'bg-[#FFECEC]',
  statusNewText: 'text-[#ba1a1a]',
  subtitle: 'text-[15px] font-bold leading-[21px] text-textMuted',
  summaryCard: 'rounded-3xl border-[#E8ECFF]',
  summaryGrid: 'mt-4 flex-row gap-3',
  summaryItem: 'flex-1 rounded-2xl bg-[#EEF3FF] p-3',
  summaryLabel: 'text-[11px] font-black uppercase text-textMuted',
  summaryValue: 'mt-1 text-lg font-black text-[#283351]',
  title: 'text-[30px] font-black leading-9 text-[#283351]'
};
