export const devicesPalette = {
  primary: '#4880FF',
  secondary: '#918BFF',
  success: '#13A36F',
  warning: '#FF8A3D',
  text: '#283351'
};

export const devicesClasses = {
  addButton: 'mt-1 flex-row items-center justify-center gap-2 rounded-2xl bg-[#4880FF] px-5 py-4',
  addButtonText: 'text-[15px] font-black text-surface',
  badge: 'flex-row items-center gap-1 rounded-full px-2 py-1',
  badgeOffline: 'bg-[#FFECEC]',
  badgeOnline: 'bg-[#E9FFF5]',
  badgeTextOffline: 'text-xs font-black text-[#ba1a1a]',
  badgeTextOnline: 'text-xs font-black text-[#13A36F]',
  cardMetric: 'flex-1 rounded-2xl bg-[#EEF3FF] p-3',
  cardMetricLabel: 'text-[11px] font-black uppercase text-textMuted',
  cardMetricValue: 'mt-1 text-lg font-black text-[#283351]',
  content: 'gap-4 bg-[#F9F8FF] p-4 pt-6 pb-[124px]',
  deviceCard: 'rounded-3xl border-[#E8ECFF]',
  deviceCardOffline: 'opacity-70',
  deviceHeader: 'flex-row items-start gap-3',
  deviceIcon: 'h-12 w-12 items-center justify-center rounded-2xl bg-[#EEF3FF]',
  deviceMeta: 'mt-4 flex-row gap-3',
  deviceMetaItem: 'flex-1 rounded-2xl bg-[#F7F8FF] p-3',
  deviceName: 'text-lg font-black text-[#283351]',
  deviceRoom: 'mt-0.5 text-sm font-bold text-textMuted',
  deviceTitle: 'flex-1',
  emptyCard: 'mt-6 items-center rounded-3xl border-[#E8ECFF] py-8',
  emptyIcon: 'h-[76px] w-[76px] items-center justify-center rounded-full bg-[#EEF3FF]',
  emptyText: 'mt-2 max-w-[280px] text-center text-[15px] font-bold leading-[22px] text-textMuted',
  emptyTitle: 'mt-4 text-center text-[22px] font-black text-[#283351]',
  filterChip: 'min-h-[40px] rounded-full border border-[#E8ECFF] bg-surface px-4 items-center justify-center',
  filterChipActive: 'border-[#4880FF] bg-[#4880FF]',
  filterChipText: 'text-sm font-black text-textMuted',
  filterChipTextActive: 'text-surface',
  filters: 'flex-row gap-2',
  header: 'gap-3',
  headerBack: 'h-10 w-10 items-center justify-center rounded-full bg-surface shadow-sm',
  headerRow: 'flex-row items-center gap-3',
  headerSubtitle: 'text-[15px] font-bold leading-[21px] text-textMuted',
  headerTitle: 'text-[30px] font-black leading-9 text-[#283351]',
  highlightCard: 'rounded-3xl border-[#918BFF] bg-[#918BFF]',
  highlightBody: 'mt-2 text-sm font-bold leading-5 text-[#F6F3FF]',
  highlightLabel: 'text-xs font-black uppercase text-[#F0ECFF]',
  highlightTitle: 'mt-1 text-xl font-black text-surface',
  offlineAction: 'mt-3 self-start rounded-2xl bg-[#FFECEC] px-4 py-2',
  offlineActionText: 'text-xs font-black text-[#ba1a1a]',
  summaryCard: 'rounded-3xl border-[#E8ECFF]',
  summaryGrid: 'mt-4 flex-row flex-wrap gap-3'
};
