export const usagePalette = {
  background: '#F9F8FF',
  primary: '#4880FF',
  primarySoft: '#EEF3FF',
  secondary: '#918BFF',
  text: '#283351',
  success: '#13A36F',
  warning: '#FF8A3D'
};

export const usageClasses = {
  barGroup: 'flex-1 items-center gap-1',
  barLabel: 'text-center text-[11px] font-extrabold text-textMuted',
  barTrack: 'h-[126px] w-full justify-end overflow-hidden rounded-2xl bg-[#EEF3FF]',
  barValue: 'text-[10px] font-black text-[#283351]',
  cardEyebrow: 'text-xs font-black uppercase text-textMuted',
  chart: 'mt-4 h-[178px] flex-row items-end gap-1',
  chartCard: 'rounded-3xl border-[#E8ECFF]',
  comparisonBadge: 'mt-1 text-[13px] font-black',
  comparisonCard: 'flex-row items-start gap-4 rounded-3xl border-[#E8ECFF]',
  comparisonContent: 'flex-1',
  comparisonDown: 'bg-[#E9FFF5]',
  comparisonDownText: 'text-[#13A36F]',
  comparisonIcon: 'h-[46px] w-[46px] items-center justify-center rounded-2xl',
  comparisonText: 'mt-1 text-base font-extrabold leading-[22px] text-[#283351]',
  comparisonUp: 'bg-[#FFECEC]',
  comparisonUpText: 'text-[#ba1a1a]',
  content: 'gap-4 bg-[#F9F8FF] p-4 pt-6 pb-[124px]',
  deviceLabel: 'mt-1 text-[13px] font-black text-[#4880FF]',
  emptyCard: 'mt-6 items-center rounded-3xl border-[#E8ECFF] py-8',
  emptyIcon: 'h-[72px] w-[72px] items-center justify-center rounded-full bg-[#EEF3FF]',
  emptyText: 'mt-2 text-center text-[15px] font-bold leading-[22px] text-textMuted',
  emptyTitle: 'mt-4 text-center text-[21px] font-black text-[#283351]',
  header: 'gap-1',
  insightCard: 'flex-row items-start gap-4 rounded-3xl border-[#918BFF] bg-[#918BFF]',
  insightContent: 'flex-1',
  insightIcon: 'h-[46px] w-[46px] items-center justify-center rounded-2xl bg-white/20',
  insightLabel: 'text-xs font-black uppercase text-[#F0ECFF]',
  insightText: 'mt-1 text-base font-extrabold leading-[23px] text-surface',
  offlineNotice: 'flex-row items-start gap-2 rounded-3xl border-[#FFE2C4] bg-[#FFF8EF]',
  offlineNoticeBody: 'mt-0.5 text-[13px] font-bold leading-[19px] text-textMuted',
  offlineNoticeText: 'flex-1',
  offlineNoticeTitle: 'text-[15px] font-black text-[#283351]',
  peakLabel: 'flex-1 text-[15px] font-extrabold text-[#283351]',
  peakRank: 'h-7 w-7 items-center justify-center rounded-full bg-[#EEF3FF]',
  peakRankText: 'text-xs font-black text-[#4880FF]',
  peakRow: 'flex-row items-center gap-2',
  peakValue: 'text-sm font-black text-[#4880FF]',
  peaksCard: 'rounded-3xl border-[#E8ECFF]',
  peaksList: 'mt-4 gap-4',
  periodTab: 'min-h-[42px] flex-1 items-center justify-center rounded-2xl',
  periodIndicator: 'absolute bottom-1 left-0 top-1 rounded-2xl bg-[#4880FF]',
  periodTabText: 'text-sm font-black text-textMuted',
  periodTabTextActive: 'text-white',
  periodTabs: 'relative flex-row gap-1 rounded-3xl border border-[#E8ECFF] bg-surface p-1',
  subtitle: 'text-[15px] font-bold leading-[21px] text-textMuted',
  summaryGrid: 'gap-4',
  title: 'text-[30px] font-black leading-9 text-[#283351]'
};
