export const deviceDetailPalette = {
  primary: '#4880FF',
  secondary: '#918BFF',
  secondarySoft: '#B8A0FF',
  success: '#13A36F',
  warning: '#FF8A3D',
  danger: '#ba1a1a',
  text: '#283351'
};

export const deviceDetailClasses = {
  actionDangerText: 'text-sm font-black text-[#ba1a1a]',
  actionIcon: 'h-10 w-10 items-center justify-center rounded-xl bg-[#EEF3FF]',
  actionRow: 'flex-row items-center gap-3 border-b border-[#EEF1FF] py-4',
  actionRowLast: 'border-b-0',
  actionText: 'flex-1 text-[15px] font-black text-[#283351]',
  actionsCard: 'rounded-3xl border-[#E8ECFF] py-0',
  alertCard: 'gap-1 rounded-2xl border-[#EEF1FF] bg-surface p-4',
  alertDate: 'text-xs font-bold text-textMuted',
  alertDescription: 'mt-1 text-sm font-bold leading-5 text-textMuted',
  alertHeader: 'flex-row items-start justify-between gap-3',
  alertSeverity: 'rounded-full px-2 py-1',
  alertSeverityHigh: 'bg-[#FFECEC]',
  alertSeverityLow: 'bg-[#EEF3FF]',
  alertSeverityMedium: 'bg-[#FFF4E8]',
  alertSeverityTextHigh: 'text-[#ba1a1a]',
  alertSeverityTextLow: 'text-[#4880FF]',
  alertSeverityTextMedium: 'text-[#B65F00]',
  alertTitle: 'flex-1 text-[15px] font-black text-[#283351]',
  chart: 'mt-4 h-[168px] flex-row items-end gap-2',
  chartCard: 'rounded-3xl border-[#E8ECFF]',
  content: 'gap-4 bg-[#F9F8FF] p-4 pb-[124px]',
  consumptionCard: 'overflow-hidden rounded-3xl border-[#4880FF] bg-[#4880FF]',
  consumptionDescription: 'mt-1 text-sm font-bold text-[#EAF0FF]',
  consumptionFooter: 'mt-5 flex-row items-center gap-2',
  consumptionLabel: 'text-xs font-black uppercase text-[#EAF0FF]',
  consumptionStatus: 'flex-1 text-sm font-black text-surface',
  emptyCard: 'mt-8 items-center rounded-3xl border-[#E8ECFF] py-8',
  emptyIcon: 'h-[76px] w-[76px] items-center justify-center rounded-full bg-[#EEF3FF]',
  emptyText: 'mt-2 max-w-[280px] text-center text-[15px] font-bold leading-[22px] text-textMuted',
  emptyTitle: 'mt-4 text-center text-[22px] font-black text-[#283351]',
  headerAction: 'h-10 w-10 items-center justify-center rounded-full bg-surface shadow-sm',
  metricGrid: 'flex-row flex-wrap gap-3',
  offlineButton: 'mt-3 self-start rounded-2xl bg-[#4880FF] px-4 py-2',
  offlineButtonText: 'text-xs font-black text-surface',
  offlineNotice: 'items-start gap-2 rounded-3xl border-[#FFE2C4] bg-[#FFF8EF]',
  offlineText: 'text-sm font-bold leading-5 text-textMuted',
  offlineTitle: 'text-base font-black text-[#283351]',
  powerRow: 'mt-1 flex-row items-end',
  powerUnit: 'mb-[8px] ml-1 text-lg font-black text-[#EAF0FF]',
  powerValue: 'text-[58px] font-black leading-[64px] text-surface',
  recommendationCard: 'rounded-3xl border-[#918BFF] bg-[#918BFF]',
  recommendationText: 'mt-2 text-sm font-bold leading-5 text-[#F6F3FF]',
  recommendationTitle: 'text-lg font-black text-surface',
  statusCard: 'flex-row items-center gap-4 rounded-3xl border-[#E8ECFF]',
  statusContent: 'flex-1',
  statusIcon: 'h-12 w-12 items-center justify-center rounded-2xl bg-[#EEF3FF]',
  statusLabel: 'mt-1 text-sm font-bold text-textMuted',
  statusName: 'text-lg font-black text-[#283351]',
  statusPill: 'flex-row items-center gap-1 rounded-full px-2 py-1',
  statusPillOffline: 'bg-[#FFECEC]',
  statusPillOnline: 'bg-[#E9FFF5]',
  statusPillTextOffline: 'text-xs font-black text-[#ba1a1a]',
  statusPillTextOnline: 'text-xs font-black text-[#13A36F]',
  summaryCard: 'flex-1 basis-[30%] rounded-2xl border-[#EEF1FF]',
  summaryIcon: 'h-9 w-9 items-center justify-center rounded-xl bg-[#EEF3FF]',
  summaryLabel: 'mt-3 text-[11px] font-black uppercase text-textMuted',
  summaryValue: 'mt-1 text-lg font-black text-[#283351]'
};
